version: "3.8"

networks:
  engineers-notebook:
    name: engineers-notebook

services:
  engineer-db:
    container_name: engineer-db
    hostname: engineer-db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - D:\test\engineer_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: devry123
      MYSQL_DATABASE: EngineersNotebook
    ports:
      - "5306:3306"
    networks:
      - "engineers-notebook"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  devry-identity:
    container_name: devry-identity
    hostname: devry-identity
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - D:\test\identity_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: devry123
      MYSQL_DATABASE: DevryIdentity
    ports:
      - "4306:3306"
    networks:
      - "engineers-notebook"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  public-api:
    container_name: public-api
    image: engineer-notebook-public-api:$TAG
    networks:
      - "engineers-notebook"
    depends_on:
      - "engineer-db"
      - "devry-identity"
    ports:
      - "5099:5099"