version: "3.8"

networks:
  engineers-notebook:
    name: engineers-notebook

services:
  engineer-db:
    container_name: engineer-db
    hostname: engineer-db
    image: mongo
    restart: always    
    volumes:
      - D:\test:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_PASSWORD: devry123
      MONGO_INITDB_ROOT_USERNAME: root
    networks:
      - "engineers-notebook"

  public-api:
    container_name: public-api
    image: engineer-notebook-public-api:$TAG
    command: ["./wait-for", "engineer-db:5306", "--", "dotnet", "EngineerNotebook.PublicApi.dll"]
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=devry123
    networks:
      - "engineers-notebook"
    depends_on:
      - "engineer-db"
    ports:
      - "5099:443"
      - "6000:80"
    volumes:
      - ${USERPROFILE}\source\repos\DeVry-Developer-Club\Engineers-Notebook\EngineerNotebook.PublicApi\appsettings.json:/app/appsettings.json
    
