name: EngineersNotebook Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
        
      - name: Build with dotnet
        run: dotnet build ./EngineersNotebook.sln --configuration Release
        
      - name: Test with dotnet
        run: dotnet test ./EngineersNotebook.sln --configuration Release